### ISSUE TITLE
Voting for "community-approved" PWA logo

### ISSUE THREAD

**Issue by webmaxru** [webmaxru/progressive-web-apps-logo#3]
Hello PWA heros!
We gathered some very nice proposals of PWA logo. Let's pick the one, we'll use as a "default".

Vote with 
![1f44d](https://user-images.githubusercontent.com/1560278/27801937-08200306-6021-11e7-94ef-8cd5c3165c76.png)
 for the option(s) you like. As a voting host, I voted for each proposal. Final date: 17.07.2017.

Please, scroll to the page bottom and review all submissions before making your decision. Logos listed in order of appearance. If you have your own proposal - please submit!

Some "good logo" criteria to help you with the selection based on something more that instant impression (from [here](https://gistbrands.net/10-must-have-logo-criteria/)):
- **Relevancy**. Does it allude to our industry, a need, or a problem we can solve?
- **Adaptability**. How well can this concept be applied in a variety of technical applications?
- **Simplicity**. Is it appropriately distilled, clean, and high-impact?

Think about some possible usecases:
- Your beautiful slides, where you list PWA logo together with other frameworks/languages ones
- Default icon (incl. 16x16) for your PWA starter project
- Sticker for your laptop
- "Badge" on top of your original app icon, to show it's a PWA

_Notice: do not take this logo/voting very seriously. This logo will never be named "official" (just because this criteria is not applicable to PWA)._

**Important**: Please [join PWA slack team](https://bit.ly/join-pwa-slack), where almost 300 web developers discuss the topic.

**Comment by webmaxru** [comment]
1. The idea-igniter proposal by @webmaxru. More or less something to just start the discussion.

![pwa-logo-small](https://user-images.githubusercontent.com/1560278/27805674-6a1e0c5a-6036-11e7-891e-1a09b764c1fd.png)

Icon usecase (16x16 goes in adapted version):
![icon-demo](https://user-images.githubusercontent.com/1560278/27805698-864ba450-6036-11e7-85aa-3e85d70d299b.png)

Some slides usecases:
<img width="455" alt="screen shot 2017-07-03 at 21 09 51" src="https://user-images.githubusercontent.com/1560278/27805713-9c924d18-6036-11e7-82e0-248e6eaf4932.png">

![logo-js](https://user-images.githubusercontent.com/1560278/27805736-c01aa6cc-6036-11e7-848f-5a335a79876c.png)

Real-life icon example:
<img width="1179" alt="screen shot 2017-07-03 at 21 11 17" src="https://user-images.githubusercontent.com/1560278/27805723-ad6f8952-6036-11e7-95e4-909cb410bed4.png">

App icon based on idea (thanks to @shprink):
![app_96](https://user-images.githubusercontent.com/1560278/27805789-10f0dbc0-6037-11e7-8440-28836125287b.png)

Badge usecase:
![badge](https://user-images.githubusercontent.com/1560278/27805930-cf4a9c1e-6037-11e7-8913-058d4a4846ce.png)

**Comment by webmaxru** [comment]
2. Proposal by @jmoont:
![pwa-logo-jmoont](https://user-images.githubusercontent.com/1560278/27806004-66ea3af2-6038-11e7-8ad9-8bd61eb79e41.png)

**Comment by webmaxru** [comment]
3. Proposal by @diekus:
![pwalogo2](https://user-images.githubusercontent.com/1560278/27806051-9e95dca4-6038-11e7-8c30-b6b98d38a6f8.png)

"W" (to emphasize the _Web_) could be in any colour. You can create your own here:
[https://diekus.net/logo-pwinter/](https://diekus.net/logo-pwinter/
)
More colours:
![pwalogo3](https://user-images.githubusercontent.com/1560278/27806069-c2a1d508-6038-11e7-97ae-c31d431c87f4.png)

Icon version:
![pasted image at 2017_06_05 04_04 pm](https://user-images.githubusercontent.com/1560278/27806082-ce485e04-6038-11e7-9e29-effa62b5fb9f.png)

More usecases:
![pwa-logo-3-updated](https://user-images.githubusercontent.com/1560278/28172556-ea57a084-67fc-11e7-8078-3f66d97b1869.jpg)

**Comment by webmaxru** [comment]
4. Proposal by @docluv:
![pwa-logo-xl](https://user-images.githubusercontent.com/1560278/27806258-bbf7fe8e-6039-11e7-9492-a47ea891a67d.gif)

![pwas3](https://user-images.githubusercontent.com/1560278/27806223-98f825c6-6039-11e7-83a9-a92b6441ebb4.gif)

More details: https://github.com/docluv/pwa-logo

**Comment by webmaxru** [comment]
5. Proposal by [@html5test](https://twitter.com/html5test)
![pwa-logo-html5test](https://user-images.githubusercontent.com/1560278/27807373-ab0592c4-6040-11e7-9e15-135e699011a2.jpg)

**Comment by webmaxru** [comment]
6. Proposal by [@felipenmoura](https://twitter.com/felipenmoura)
![pwa-logo-6](https://user-images.githubusercontent.com/1560278/27807405-d78391ca-6040-11e7-9773-1b7c15eff9e4.png)

**Comment by webmaxru** [comment]
7. Proposal by [@alexey_rodionov](https://twitter.com/alexey_rodionov)

Playing with combination of rocket + other frameworks:
![pwa-logo-preview](https://user-images.githubusercontent.com/1560278/27824017-5d53fafa-60ab-11e7-8053-9cc484dd8ac4.png)

Ionic PWA
![ionic-pwa-logo-preview](https://user-images.githubusercontent.com/1560278/27824021-63e6dcb6-60ab-11e7-83dc-31daa21feea0.png)

React PWA
![react-pwa-logo-preview](https://user-images.githubusercontent.com/1560278/27824039-6efbb126-60ab-11e7-83ab-6807bf46e88b.png)

**Comment by melanierichards** [comment]
Here's an idea I was talking to some coworkers about. Inspired by the idea of a PWA being ever-fresh / up-to-date. The icon could animate to expand and fit the full phrase, but the mechanics of that can be worked out later!

![pwa-icon-presentation](https://user-images.githubusercontent.com/340395/28044565-fdcb412e-658c-11e7-831d-ed61802ea6a7.png)

**Comment by clagom** [comment]
Hello,

Here is a proposal for the Progressive Web App logo mark, playing around with the letters PWA in a graphic way.

<img width="1036" alt="pwa logomark" src="https://user-images.githubusercontent.com/1953388/28131536-1af9855c-6732-11e7-9a64-eff4f05014c6.png">

With this logo mark would be possible to create a recognisable pattern to use across different media and communication material.

<img width="1417" alt="sample" src="https://user-images.githubusercontent.com/1953388/28131644-78b330da-6732-11e7-85cc-dceb97fdf41f.png">

Application icons would be inspired by the shapes, and still be recognisable with the brand.
![android](https://user-images.githubusercontent.com/1953388/28131675-8d950870-6732-11e7-952e-43339ac625c0.jpg)

![card-mockup](https://user-images.githubusercontent.com/1953388/28131658-80c4108c-6732-11e7-9275-bff280de2f54.jpg)

![t-shirt](https://user-images.githubusercontent.com/1953388/28131666-85a55e94-6732-11e7-86af-55ac04ca3f90.jpg)

Wallpaper and business card with the graphic pattern:
![mockup01](https://user-images.githubusercontent.com/1953388/28132721-8c82c8fc-6735-11e7-9ea2-77d7a958a0a4.jpg)

![card-mockup2](https://user-images.githubusercontent.com/1953388/28132620-48fd0200-6735-11e7-8fa4-2163e17266d9.jpg)

![wallpaper](https://user-images.githubusercontent.com/1953388/28132439-c49487d6-6734-11e7-92df-6de5d545efc7.jpg)

![wallpaper](https://user-images.githubusercontent.com/1953388/28219171-ebaba578-68b2-11e7-9568-dd2f09b7d805.gif)

**Comment by diekus-zz** [comment]
nice designs by the community :)

I've put together some use cases of the logo entry #3 based on some questions I've received. Hope it helps!  @webmaxru if you can edit my entry and add this pic it'd be great!

![pwalogofinal](https://user-images.githubusercontent.com/3104648/28170741-2f0b1536-67de-11e7-8454-5bb8961fa0fe.jpg)

**Comment by webmaxru** [comment]
@diekus: my pleasure to update your original proposal
@everyone: please vote for @diekus logo in original comment ( https://github.com/webmaxru/progressive-web-apps-logo/issues/3#issuecomment-312721722 ), likes in extra comment (above this one) are not counted (but you are welcome to give kudos to this awesome addition anyway :)

**Comment by webmaxru** [comment]
July 17th is eventually over, and **the winner is**...

@diekus (Samsung Internet browser team) with his bold and universal proposal (82 thumb-ups!): https://github.com/webmaxru/progressive-web-apps-logo/issues/3#issuecomment-312721722 !
![screen shot 2017-07-18 at 13 31 54](https://user-images.githubusercontent.com/1560278/28315135-84fbbd14-6bbd-11e7-87ea-1366d6868747.png)

@diekus: you are welcome to publish once again all we need to start using the logo:
- Image in different formats
- Usage guide
- Different usecases
- I personally can't wait to see the printed stickers :)

@everyone:
- I want to thank all participants (incl. me :) @webmaxru (3rd place, 33 thumb-ups), @jmoont, @diekus, @docluv, @html5test, @felipenmoura, @alexey_rodionov, @melanierichards, @clagom (super-trending option, 2nd place, 75 thumb-ups!): **great contributions, folks!**
- Specials thanks go to voters - 225 thumb-ups in total!
- And congratulations to the winner and all of us! Progressive Web Apps have a community-approved logo now, and it's simple, useful and beautiful!

_Important:_ This is not an official logo, this term is not applicable to PWA as an entity. You are free to accept or not the selected logo, as well as you are welcome to use any other one.

I unlock the comments again, so the vote numbers could be different from the mentioned above.

Everyone is welcome to join **PWA slack team**. More than 300 developers hold technical discussions about Progressive Web Apps there: https://bit.ly/join-pwa-slack

**Comment by grigs** [comment]
@clagom Are you ok with people using your logo treatment even if it wasn't the official one? If so, will you upload source files?

**Comment by clagom** [comment]
@grigs Hello! Sure, here is the original file in PDF, it can be opened in Illustrator or other vector programs like Inkscape:
[PWA.pdf](https://github.com/webmaxru/progressive-web-apps-logo/files/1159089/PWA.pdf)

The font used is "Clear Sans", open source, and can be downloaded from here:
https://01.org/clear-sans

**Comment by felipeblini** [comment]
Awesome logo, just loved it
