### ISSUE TITLE
PWA logo guide and sources

### ISSUE THREAD

**Issue by diekus-zz** [webmaxru/progressive-web-apps-logo#4]
# "Community-Approved" PWA logo

![pwa](https://user-images.githubusercontent.com/3104648/28351989-7f68389e-6c4b-11e7-9bf2-e9fcd4977e7a.png)

PWA letters with an emphasis on the "W" with different colors, textures or graphics. The cuts between the letters remind of the // in the URL. It can be used in dark or light fonts, and can easily be adapted into icons, stickers, or other use cases.

Logo is based in a dark or light font, in order for it to adapt to many use scenarios. It can be used in any color. It is suggested that the W stands out in order to highlight the "Web" part of PWA. Nonetheless all three letters in one looks also great! It is your logo, feel free to adapt it. Base colors are:

![base colors](https://user-images.githubusercontent.com/3104648/28351783-ea1e2506-6c49-11e7-8295-2bcc76ba8201.png)

## Vector source:

The easiest way to start using the logo is getting a vector file. You can create and download your own SVG file with color combination at [https://diek.us/logo-pwinter/](https://diek.us/logo-pwinter/) (also a PWA!)

![capture](https://user-images.githubusercontent.com/3104648/28352657-9d13b9a0-6c4f-11e7-8e8c-1b55e9d4d07a.PNG)

## Demo example usage:
![ew](https://user-images.githubusercontent.com/3104648/28351863-96b13a74-6c4a-11e7-9ed9-1f021c36385e.jpg)

It can be used with other logos (examples here show different browsers that support PWAs, a React version, or a WebVR like app that itself is a PWA. You can play around and put your company logo as well.) Looks great for stickers!

### High Res PNG: (2048px width)

![pwa](https://user-images.githubusercontent.com/3104648/28352004-a055292c-6c4b-11e7-9c6b-a94cdc2a5458.png)

![pwaw](https://user-images.githubusercontent.com/3104648/28352065-2f94fba8-6c4c-11e7-9536-3d8e249e048f.png)

### High Res JPG: (2048px  width)

![pwa](https://user-images.githubusercontent.com/3104648/28352019-c0aea0ea-6c4b-11e7-97f2-eb3cc28c6db0.jpg)

### High Res GIF: (2048px width)

![pwa](https://user-images.githubusercontent.com/3104648/28352033-e453b5bc-6c4b-11e7-95eb-2fcac2e84e6e.gif)

![pwaw](https://user-images.githubusercontent.com/3104648/28352047-0a085920-6c4c-11e7-9b9c-c0d428ba66a1.gif)

## SVG Source File Download

[http://diekus.net/images/PWA_LOGO_SOURCE.svg](https://github.com/diekus/logos-repo/tree/master/PWA)

## Tip

Get creative. This logo will look great in any environment you put it on. That's what it was made for. :) Enjoy!

![pwasw](https://user-images.githubusercontent.com/3104648/28352346-cd52892c-6c4d-11e7-9052-007a9f4f956c.png)

Feel free to post and share remixed uses and creations in the comments. Would love to see how the logo, as the PWA themselves, adapt to different scenarios like slides, posts, and swag. :)

### License
The licence is [ https://creativecommons.org/share-your-work/public-domain/cc0/ ](https://creativecommons.org/share-your-work/public-domain/cc0/), i.e. dedicated to the public domain.

**Comment by Raincal** [comment]
![vue pwa](https://user-images.githubusercontent.com/6279478/28391719-aa7eda02-6ca4-11e7-8362-c7ea45f81ca9.png)

**Comment by DavidFrahm** [comment]
(Not sure if this belongs here or separate issue.)

I would like to suggest we have a standard app badge also. This logo is great for all kinds of things, and if it could be worked into something users would recognize as an app store badge that would help for marketing pages and content.

So something utilizing this logo, but as similar as possible to these badges from Apple and Google:

![image](https://user-images.githubusercontent.com/889791/28948352-c39851da-787a-11e7-926c-ce22dc8d00c3.png)

For illustration purposes only, here's a rough concept:

![image](https://user-images.githubusercontent.com/889791/28948562-157309fe-787c-11e7-885c-7d85e5f6f513.png)

**Comment by diekus-zz** [comment]
@DavidFrahm 

Hi, That's a good idea. Slightly trickier cause there are several versions around of those type of badges. Nonetheless, I did manage to find the official Google Play and App Store badges here (https://play.google.com/intl/en_us/badges/ & https://developer.apple.com/app-store/marketing/guidelines/#downloadOnAppstore) making it easier to do one that fits similar specs. 

I am uploading a basic one with the "W" in a slight grey, then again, if it is needed to change the color of the W to make it match a custom design or site, you can edit the SVG file attached. 

TEST:
![pwalogofinal](https://user-images.githubusercontent.com/3104648/28969232-a0f244be-791b-11e7-9e56-e1eac6000727.png)

HI RES READY TO USE PNGS
PURPLE:
![pwabadge1](https://user-images.githubusercontent.com/3104648/28969264-d14f6178-791b-11e7-9399-e7820d6aaa39.png)

GREY:
![pwabadge2](https://user-images.githubusercontent.com/3104648/28969272-d8135ffa-791b-11e7-8cf2-7ff9414b281a.png)

SVG file: 
![https://github.com/diekus/diekus.github.io/blob/master/downloads/pwalogo/pwaNeutralBadge.svg](https://github.com/diekus/diekus.github.io/blob/master/downloads/pwalogo/pwaNeutralBadge.svg)

![https://github.com/diekus/diekus.github.io/blob/master/downloads/pwalogo/pwaPurpleBadge.svg](https://github.com/diekus/diekus.github.io/blob/master/downloads/pwalogo/pwaPurpleBadge.svg)

Would this work? Any suggestions or comments?

**Comment by DavidFrahm** [comment]
Wow, this is cool. The only thing I see is that because its all text, people might try to read it as: "Progressive PWA Web App".

What if you made the lefthand PWA logo seem more like the Apple/Google badges where its more icon/logo-ish? You could also add some contrast to the words by inverting it to be like a white shape with light and dark gray "PWA"?

**Comment by DavidFrahm** [comment]
Do you think the right side wording needs to be "Progressive"?

Just noticing how Apple/Google's is something actionable with "Get it on" and "Download on the".

So something like "Launch now on/in/as"? Highlight the immediate discovery and availability of a PWA?

Sorry - I might be having too much fun with this ;)

**Comment by diekus-zz** [comment]
Good points. I think just by putting the logo in a color this is fixed. Or putting it on an icon shaped outline. About the wording, that's an interesting point. Main problem is that "Google Play" and "App Store" are quite shorter than "Progressive Web Apps" so that might be a mouthful to put in the second line and get a consistent look in font size. 

Something like this? 
![pwabadge3example](https://user-images.githubusercontent.com/3104648/28971167-ef90a94c-7922-11e7-998a-8f38b4e61cea.png)

app like icon is a nice wink at home screen capabilities?

**Comment by diekus-zz** [comment]
@DavidFrahm https://twitter.com/diekus/status/893468287652286468

**Comment by gabfiocchi** [comment]
Hello everyone! We have read the comments that have been made previously and we want to contribute with our proposal!

![bundle_pwa](https://user-images.githubusercontent.com/9122190/28998409-c5bf7362-7a00-11e7-9b63-db56694522e7.png)

We also think that the text can be slightly shortened to highlight further action:

![bundle_pwa](https://user-images.githubusercontent.com/9122190/28998498-0df3c0c8-7a03-11e7-8780-2c71d0b3330e.png)

**Comment by webmaxru** [comment]
Moved to README.md

**Comment by franklinz89** [comment]
![28971167-ef90a94c-7922-11e7-998a-8f38b4e61cea](https://user-images.githubusercontent.com/25647254/61242100-7cfd5700-a70a-11e9-9026-4ff126625d30.png)

**Comment by LuisReinoso** [comment]
I made this recently :D

![pwa-logo](https://user-images.githubusercontent.com/7484215/74991023-dc46e680-5412-11ea-80ce-ff4a234fcb93.png)

**Comment by Quethzel** [comment]
@diekus the svg links are down

**Comment by diekus-zz** [comment]
@Quethzel thanks for the heads up. I've created a repo to keep them accessible throughout all my many website redesigns XD. 

you can find them here https://github.com/diekus/logos-repo/tree/master/PWA

**Comment by andylib93** [comment]
@gabfiocchi do you have the svg version of your 'launch as web app' banners? I'm not a great fan of .png

**Comment by gabfiocchi** [comment]
yes, let me find it, I will update early

**Comment by vitorblsantoss** [comment]
White Version
[
![pwa-1](https://user-images.githubusercontent.com/85585990/147482139-a3928e64-a4ef-4bc0-a77c-881e15fedf39.png)
](url)

**Comment by gabfiocchi** [comment]
Hello everyone, I have uploaded the assets so that everyone can download them


https://github.com/gabfiocchi/progressive-web-apps-logo/tree/master/assets
