### ISSUE TITLE
Invite link is no longer active

### ISSUE THREAD

**Issue by tgmarinho** [webmaxru/progressive-web-apps-logo#6]
https://progressive-web-apps.slack.com/join/shared_invite/MjA0MzY4NjYzOTg2LTE0OTg1ODQ5NjUtYTUyZTM4MzA0Nw

This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available.

**Comment by webmaxru** [comment]
The correct link (shortened) is https://bit.ly/go-pwa-slack

Could you please point to the place where the wrong link placed?

**Comment by tgmarinho** [comment]
Thank you @webmaxru, sorry I don't remember where I find it, though. If I find again I'll ping in here.

**Comment by dartess** [comment]
@webmaxru https://bit.ly/go-pwa-slack — This link is no longer active
https://progressive-web-apps.slack.com/ is alive? can i get there?

**Comment by webmaxru** [comment]
Hello @dartess!
Please try this link: https://aka.ms/pwa-slack
